services:
  app:
    image: ruuturetki-front
    build:
      context: ./ruuturetki-frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URI=http://server:3001
    volumes:
      - ./ruuturetki-frontend/:/usr/src/app
    container_name: ruuturetki-front
    ports:
      - 3000:3000 # this is needed
  server:
    image: ruuturetki-back
    build:
      context: ./ruuturetki-backend
      dockerfile: Dockerfile
    volumes:
      - ./ruuturetki-backend/:/usr/src/app

