services:
  front:
    image: ruuturetki-front
    build:
      context: ./ruuturetki-frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URI=https://api.ruuturetki.fi
    container_name: ruuturetki-front
    ports:
      - 3000:3000 
    restart: always
  back:
    image: ruuturetki-back
    build:
      context: ./ruuturetki-backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    restart: always

