services:
  front:
    image: ruuturetki-front
    build:
      context: ./ruuturetki-frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URI=http://localhost:3001
    container_name: ruuturetki-front
    ports:
      - 3000:3000 
  back:
    image: ruuturetki-back
    build:
      context: ./ruuturetki-backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001

